# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            艾莉亚的猫
tagline:          'Time is limited, To be a better man'
description:      'Hello,World! Here is my personal weblog about technology and life.'
url:              http://yangtze736.github.io/

author:
  name:           'yangtze'
  url:            https://github.com/yangtze736

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : yangtze
